import time
print("this is a dummy file")
time.sleep(5)
print("is does nothing")
time.sleep(5)
print("maybe it will do something in the future")
time.sleep(5)
print("or maybe not")
time.sleep(5)
print("it depends on my collaborator")